# Generated by Django 4.2.3 on 2023-07-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publication',
            new_name='public',
        ),
    ]
